[package]
name = "toy-bnf"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.21", default-features = false, features = ["derive", "std", "help", "usage"] }
logos = "0.15.0"
thiserror = "2.0.8"
